jackaudio/jack2

posix/JackPosixServerLaunch.cpp
allow autostart of jackd on OSX where device-names can
contain spaces.
=> support [unescaped] double-quotes in jackdrc

common/JackGenericClientChannel.cpp
Overwriting causes the previous status to be lost. This results in an incorrect status returned to calls of jack_client_open.
This behavior can be reproduced by running the example client simple_client without a running jackd instance. It will not print the "JACK server started" message, while it does start the server. This is because of the status getting overwritten by the status of the ClientCheck call on JackEngine.
=> Preserving original status

example-clients/wscript
Dear all,
typo fixed:
jack_showtime application was duplicated in wscript.
Thanks,
KimJeongYeon
=> eliminate duplicated examples.

common/wscript, example-clients/wscript, linux/wscript, windows/wscript, wscript
After the previous pull request https://github.com/jackaudio/jack2/pull/110 we decided it would be good to have option in the build system that can have two states 'yes' and 'no'. That is implemented in this pull request. Some options can now be specified as --foo=yes or --foo=no to enable and disable foo respectively. The old form --foo is interpreted as --foo=yes. Together with other fixes and improvements. This pull includes the following:
1. Implementation of (and some fixes to) the AutoOptions class that is the logical backone for all options.
2. Move from old option to auto options where appropriate, i.e. an option can be enabled by default and has external dependencies.
3. Automagic depdendencies (see [1] for more info on these) on celt, opus, samplerate, sndfile and readline has …
=> Auto options and removed automagic dependencies

doxyfile.in, wscript
The install phase fails with doxygen enabled since doxygen generates html to the html directory directly under the top source directory. Not only is this bad (build files in source directory!), but it made installation fail when waf thought that html docs reside in build/default/html. This pull request fixes this issue by generating the doxyfile from a template, doxyfile.in. This makes it possible for wscript to subst correct directories into doxyfile. The manual invokation of doxygen was removed in favour of a waf rule (which is necessary since it now must depend on doxyfile). Also doxygen output has been piped into a log file for various reasons.
There was an other fault that made the uninstall phase fail (because share_dir was defined on the wrong place). This is fixed too.
As a goodie …
=> Doxygen fixes, less hardcoding and --htmldir

example-clients/transport.c, example-clients/wscript, wscript
These small fixes are necessary for successful build using waf with mingw-w64 when cross compiling on linux(tested with Fedora) and using MSYS2 environment on windows.
=> Mingw waf fixes

svnversion_regenerate.sh, wscript
The svnversion.h was broken since the dist_hook was never called. This resulted in SVN_REVISION being defined as "unknown" (since svnversion.h did not exist and not the .git directory either) in distributed tarballs. This pull request fixes that issue.
Also the svnersion_regenerate.sh script assumed ../ was the source directory. It has been fixed.
Another issue was the hardcoded path to the svnersion_regenerate.sh script which caused builds with a nonstandard out directory (--out was specified and was not build) to fail. This is also fixed.
There are a few very minor fixes too such as future-proofing so that cxx sources can use svnversion.h to.
=> Fix svnversion.h generation

common/JackClient.cpp
return value of JackGenericClientChannel->SetTimebaseCallback() instead
of -1 where there is a conditional request
This should close issue : 122
https://github.com/jackaudio/jack2/issues/122
=> Fix return value of SetTimebaseCallback()

example-clients/bufsize.c
Since help and error messages suggest, that 8192 samples is a valid
buffer size, this fixes the value in the check to 8192 instead of 8182.
=> [jack_bufsize] Fix off by 10 error

common/JackNetManager.cpp
The network manager is setting their ports' latencies in the other mode, I think.
A `to_slave` port should have its playback latency setup on the latency callback,
and a `from_slave` port should have its capture latency setup.
=> Correct netmanager latency reporting

linux/alsa/alsa_rawmidi.c
The midi thread was always late after 2^31-1 Samples (~13.5h at 44.1kHz), because when there's no time limit, a uint64_t sample counter was compared against a signed 32bit INT_MAX to determine lateness. Now the CPU lockup will occur only after ~3 million years (at 192kHz), and because of the overflow it will presumably fix itself after a few milliseconds. Fixes #150
=> Fix CPU hogging of the midi_thread()

linux/alsa/JackAlsaDriver.cpp
Call JackAlsaDriver::Close() when alsa_driver_new() fails, to
release devices acquired just before that call. Otherwise
JackAlsaDriver::Open() will never succeed again, as re-acquiring the
same device will fail with "A handler is already registered" DBus error.
=> Release audio devices when alsa_driver_new fails

common/JackNetTool.h
Part of 02f74a659 touched the `_session_params` struct, breaking the alignment and causing both ends (driver and manager) to crash at negotiation. ~~This reverts the relevant change.~~
=> Fix Netjack crashes due to broken alignment

man/fill_template
this enables making reproducible builds of this package
see also https://reproducible-builds.org/specs/source-date-epoch/
This change is tested.
Related to https://github.com/jackaudio/jack1/pull/38
=> allow to use source date for man page generation

dbus/sigsegv.c
When compiling jack on nios2, compilation fails because NGREGS is not
defined. Since this is only for debug output on segmentation faults, stub
the debug print out like it's been done for other platforms before.
Inspired by
https://github.com/jackaudio/jack2/commit/d11bb095291d8880508c87adfe625bf2bcab1456
Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
=> Add support for nios2

common/jack/systemdeps.h
This is an old bug from here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=728710
Not all MIPS processors support unaligned access (although some do) so using packed structures is not safe on this platform.
=> Don't pack structures on MIPS where unaligned access is not allowed

dbus/sigsegv.c, wscript
The ucontext functionality is not available on all CPUs with all C
libraries. Instead of making just assumptions based on the CPU
architecture, this commit adds the necessary checks in wscript to verify
the availability of the ucontext functionality, before using it in
dbus/sigsegv.c.
This avoids the long list of architecture exclusions, and make it more
robust when building jack2 for new CPU architectures.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
=> wscript: improve check for ucontext

example-clients/transport.c
There was a thread in the linuxaudio users list about how to toggle the jack transport state between play and stop using the keyboard.
As they were already using jack_transport to set the state but needed to write a script to get the current transport state with jack_showtime I thought there might be a better solution.
Holger
=> Toggle between run and stop state

dbus/sigsegv.c, wscript
In some C-libraries (like uclibc), backtrace support is optional, so the
execinfo.h may not exist.
This change adds the check for execinfo.h header and conditionaly enable
backtrace support.
This issue has been triggered by Buildroot farms:
http://autobuild.buildroot.org/results/391/391e71a988250ea66ec4dbee6f60fdce9eaf2766/build-end.log
Signed-off-by: Samuel Martin s.martin49@gmail.com
=> Make backtrace support depends on execinfo.h existence

common/memops.c
a leading 1 was missing [1]
[1] http://www.musicdsp.org/showone.php?id=59
Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
=> fix copy & paste bug on dither rambdom generator

common/memops.c, example-clients/simdtests.cpp, example-clients/wscript
The second patch adds an application to check accuracy/performance of accelerated code compared to original code (should be working with SSE too - but this was not tested). The application outputs on RaspberriPi2:
JackFloat->Integer @ 32u24s/1: Orig 0.076473 sec / Accel 0.010730 sec -> Win: 612.70 %
Value error sample 13: Orig 0x80C148 Accel 0x80C149
Value error sample 14: Orig 0x810290 Accel 0x810291
Value error sample 20: Orig 0x828A3E Accel 0x828A3F
Value error sample 26: Orig 0x8411EC Accel 0x8411ED
Value error sample 32: Orig 0x85999A Accel 0x85999B
Value error sample 33: Orig 0x85DAE2 Accel 0x85DAE3
Value error sample 38: Orig 0x872148 Accel 0x872149
Value error sample 39: Orig 0x876290 Accel 0x876291
Value error sample 45: Orig 0x88EA3E Accel 0x88EA3F
Value error sample 51: Orig …
=> ARM Neon support for non-dithering sample conversion functions

posix/JackPosixSemaphore.cpp
Observed a crash in JackPosixSemaphore::Wait where fSemaphore was null yet sem_wait() was still being called.
These patches add the null pointer check from the commented wait function, as well as performing some code clean up by removing said commented function.
=> Fix crash in JackPosixSemaphore::Wait

tests/iodelay.cpp
With glibc 2.16, we get following build error when building jack2:
[193/247] cxx: tests/iodelay.cpp -> build/tests/iodelay.cpp.4.o
../tests/iodelay.cpp:171:43: error: 'UINT32_MAX' was not declared in this scope
../tests/iodelay.cpp:171:55: error: 'UINT32_MAX' was not declared in this scope
../tests/iodelay.cpp:172:44: error: 'UINT32_MAX' was not declared in this scope
../tests/iodelay.cpp:172:56: error: 'UINT32_MAX' was not declared in this scope
In glibc 2.17 or older version, Header <stdint.h> defines these macros
for C++ only if explicitly requested by defining __STDC_LIMIT_MACROS.
We can't use <cstdint> since it requires C++11 standard.
This build issue found by Buildroot autobuilder.
http://autobuild.buildroot.net/results/369/369ce208ffea43dad75ba0a13469159b341e3bf5/
Signed-off-by: …
=> tests: define __STDC_LIMIT_MACROS

example-clients/ipload.c
This PR adds a 'autoclose' option to jack_load.
This is so that the initial process that called jack_load gets terminated if someone else called jack_unload.
Current code was left as-is as much as possible, so we don't change the previous behaviour.
=> Add autoclose option to jack_load

common/wscript, linux/JackLinuxFutex.cpp, linux/JackLinuxFutex.h, linux/JackPlatformPlug_os.h
The current use of posix semaphores in the jack2 code is wrong.
See https://sourceware.org/bugzilla/show_bug.cgi?id=17980
> The type sem_t has never been compatible between 32-bit and 64-bit processes, neither size nor alignment match.
The old "working" behavior was never officially supported.
This patch adds a new class that uses a linux futex as JackSynchro, and makes it the default for linux builds.
I made it so that internal clients use the 'private' futex flag, this is specially useful in ARM systems where context switches are very expensive.
Fixes #183.
PS: I've been testing this change myself for more than a month, and it is now the default on the KXStudio repositories.
Everything working nicely so far.
=> Use linux futex as JackSynchro

example-clients/alsa_in.c, example-clients/alsa_out.c
`alsa_in` and `alsa_out` set the playback latency of their ports to the target delay. The problem is the target delay is in terms of the _ALSA sample rate_, so it should be converted to JACK's sample rate.
Example: Imagine JACK is running at 48 kHz, and `alsa_out` is invoked like:
```
alsa_out -r 96000 -t 512
```
Currently, `alsa_out` will report 512 frames of playback latency. After the fix, it converts to 48kHz and correctly reports 256.
Also converts the result of `jack_frames_since_cycle_start` to ALSA sample rate.
=> alsa_in/out: Convert between sample rates when necessary

common/JackNetTool.h
`PACKET_AVAILABLE_SIZE` now also subtracts `UDP_HEADER_SIZE`, to prevent NetJack from sending too long packets.
=> Account for IP+UDP header in MTU

common/JackNetTool.cpp
Missing parentheses in `JackNetTool.cpp`, see patch.
=> Correct typos in JackNetTool.cpp

common/memops.c
This generates a warning with newer versions of GCC. This is in no way a major change, it just makes things a little bit safer.
=> Fixed a compiler warning in the memops.c file.

common/JackDriverLoader.cpp, common/wscript, windows/JackCompilerDeps_os.h, windows/JackSystemDeps_os.h, windows/portaudio/JackPortAudioDriver.cpp, wscript
- Make locate_dll_driver_dir() independent from the dll file name.
- Add setenv() and unsetenv(), which are used in JackProxyDriver.cpp (Windows does not have them).
- Miscellaneous fixes.
I've tested this patch on MSYS2, with prebuilt PortAudio MSYS2 package, which supports WASAPI.
The PortAudio MSYS2 package seems to use these patches:
<https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-portaudio>
=> Fix some issues on Windows.

common/promiscuous.c, common/promiscuous.h, common/shm.c, common/wscript, linux/JackLinuxFutex.cpp, linux/JackLinuxFutex.h, posix/JackPosixSemaphore.cpp, posix/JackPosixSemaphore.h, posix/JackSocket.cpp, posix/JackSocket.h
This is a rework of PR #77 
Promiscuous mode requires that all clients are launched with a way too permissive 0000 umask.
With this PR, permissions are explicitly set on various shared resources so it is unnecessary to temper with the umask.
Moreover, it is possible to pass a group name or a gid in the JACK_PROMISCUOUS_SERVER environment variable so that the permissions on those resources are restricted to the members of a specific group.
=> Secure promiscuous mode

common/JackAudioDriver.cpp, common/JackClient.cpp
As discussed on the jack-devel list, these are probably copy&paste style bugs.
=> fixed potential copy&paste style bugs

posix/JackPosixThread.cpp
This prevents jack control threads from inheriting RT priorities from other applications that may be using this in another RT thread
=> Use PTHREAD_EXPLICIT_SCHED for non RT threads

posix/JackNetUnixSocket.cpp
Set the ToS/DS field on the packets sent over the network (the code was commented out for some reason).
This should make most network hops prioritize Netjack2 packets over other kinds of traffic.
=> Set ToS on Netjack2 packets

linux/alsa/JackAlsaDriver.cpp, linux/alsa/JackAlsaDriver.h, linux/alsa/alsa_driver.c, linux/alsa/alsa_driver.h
This is required for example for some adaptive sample rate converters
which are executed on top of JACK. These SRCs are using the time stamp to
calculate the buffer fill level between playback application and sound
card.
=> alsa driver: Provide option to enable time stamp mode for all devices

common/Jackdmp.cpp, wscript
With this patch it is possibly to start the JACK daemon with a systemd
service file of type notify. The following provides an example service
file:
[Service]
Type=notify
ExecStart=/usr/bin/jackd -d alsa
[Install]
WantedBy=multi-user.target
=> jackdmp: Signal to systemd when ready

man/jackd.0
additions:
-firewire backend options
-note about JACK name
-links to JACK github page, mailinglist, ffado.org
-manpage author
-note about how to create pdf from manpage
removals:
-dead/unavailable links
formatting:
-remove double spaces after '.'
-all urls are bold, enclosed in <>, ending with / if it's not a file
-(non-printable) empty lines between sections for better overview
other:
-partial rewording of main paragraph. misc small changes (see diff).
=> Update manpage: Add Firewire backend options & more

common/JackNetOneDriver.cpp, example-clients/metro.c, example-clients/midiseq.c, linux/alsa/alsa_driver.c, linux/alsa/alsa_seqmidi.c, linux/alsa/hdsp.c, posix/JackNetUnixSocket.cpp, tests/cpu.c, tests/test.cpp
Since I am mostly hacking in the build system I thought it would be a good idea to let you review these changes in a pull request before pushing to master.
This fixes some (I am not compiling all features so I assume not all) unused-variable and unused-but-set-variable compiler warnings. The fixes are naive, i.e. the variables have been dropped without further ado.
=> Fix unused{,-but-set}-variable compiler warnings.

android/Shm.cpp, common/JackTools.cpp, common/shm.c
I was trying to use a setuid jack_lsp and it didn't work, presumably because of this - maybe not the most common use case, but I think its helpful to support.
=> Allow for effective UID of binaries

common/JackAudioPort.cpp, common/memops.c, example-clients/simdtests.cpp
Without this PR simd optimization will not used for ARMv8.
GCC defines __ARM_NEON__ for asimd on ARMv7 and __ARM_NEON for simd on
ARMv8. Therefore also check for __ARM_NEON.
=> arm64: Enable simd implementations

common/memops.c, common/memops.h, example-clients/alsa_in.c, example-clients/alsa_out.c, linux/alsa/alsa_driver.c, solaris/oss/JackBoomerDriver.cpp, solaris/oss/JackOSSAdapter.cpp, solaris/oss/JackOSSDriver.cpp
ALSA expects right-aligned (0x00******) samples when using S24_LE and S24_BE but without this PR JACK converts into left-aligned samples (0x******00). This can result in clipping when the amplitude is higher than 0x7FFF.
In addition the same conversion was also used for S32_LE and S32_BE. Therefore the full range of S32_LE was not used. The maximal value of JACK was 0x7FFFFF00 but the maximal value accepted by ALSA is 0x7FFFFFFF. This PR provides separated conversion functions for S32 (inlining is used to reduce duplicates).
I have compiled it for ARM64 and x86_64.
=> float2int: Use right S24 format and full range S32 format

common/memops.c, common/memops.h, example-clients/alsa_in.c, example-clients/alsa_out.c, linux/alsa/alsa_driver.c, solaris/oss/JackBoomerDriver.cpp, solaris/oss/JackOSSAdapter.cpp, solaris/oss/JackOSSDriver.cpp
This s about to revert ALL of the following series of commits, as given by:
```
> git log --oneline  c5a0f5ea...831163e5^
c5a0f5ea oss_driver: Use float to S32 conversion if requested
148c8d8e alsa_in/out: Use float to S32 conversion if requested
d017e1ff alsa_driver: Use float to S32 conversion if requested
bb99e09b memops: Provide function for float to S32 conversion
b4ea23df memops: Align S24LE and S32LE to float conversion
244fc27e memops: Provide function for S32 to float conversion
4455fe02 memops: Align float to S24LE and S32LE conversion
a82f3f2f memops: Remove not used conversion macros
e7532543 memops: Use right-aligned S24LE to float conversion
831163e5 memops: Use right-aligned float to S24LE conversion
```
Apparently at least one of the above is causing severe sound anomalies …
=> memops-alsa_bad_sound-fix-1

dbus/controller.c, dbus/wscript, linux/uptime.c, linux/uptime.h, macosx/uptime.c, macosx/uptime.h
I have a problem while compiling jack2 on macOS X with dbus support because sysinfo.h is a linux exclusive.
I used sysctl on macOS to get uptime and it just works.
=> Solving problems while compiling jack2 on macOS X with dbus support

common/JackNetOneDriver.cpp, common/JackTools.cpp
JackTools is a part of the LGPL licenced jacklib and should not pull in
GPL licensed code.
=> Remove GPL dependency from JackTools.

common/JackControlAPI.cpp
A simple example calling jackctl_server_create, open, start, stop, close and finally destroy will leak memory allocated for parameter constraints. 
With this fix asan does not report any leaks when loading the "jack_dummy.so" driver.
=> Fix memory leak of parameter constraints.

common/JackRequest.h
Increase property key field length, from JACK_UUID_STRING_SIZE (37) to MAX_PATH+1 (256), as long to fit most metadata keys (URI) on change notification/callback requests.
=> [metadata] Fix property key length to notification/callback requests.

common/jack/metadata.h
AFAICT, that's the actual behavior.
Same change for JACK1: https://github.com/jackaudio/headers/pull/8
=> DOC: Update docs for jack_get_all_properties()

posix/JackSocket.cpp
Since alsa-plugins >= 1.1.7 now enables the ALSA jack plugin by default with 50-jack.conf, I've been seeing sporadic crashes in Kodi when the sound devices get reenumerated for a udev event. I traced this down to a double close on the audio engine thread concurrent with a close on the udev thread which asserts on EBADF in libudev causing the crash.
An strace pointed to the double close occuring in posix/JackSocket.cpp:139 and posix/JackSocket.cpp:158.
To fix this, reset fSocket to -1 after closing on an error to prevent a double close later.
Signed-off-by: Joe Yasi <joe.yasi@gmail.com>
=> Set fSocket to -1 after close on an error to prevent a double close.

common/JackEngine.cpp, common/JackEngine.h, common/JackLibAPI.cpp, common/JackLockedEngine.h, common/JackMetadata.cpp, linux/alsarawmidi/JackALSARawMidiDriver.cpp, linux/alsarawmidi/JackALSARawMidiInputPort.cpp, linux/alsarawmidi/JackALSARawMidiInputPort.h, linux/alsarawmidi/JackALSARawMidiOutputPort.cpp, linux/alsarawmidi/JackALSARawMidiOutputPort.h, linux/alsarawmidi/JackALSARawMidiPort.cpp, linux/alsarawmidi/JackALSARawMidiPort.h, macosx/coremidi/JackCoreMidiDriver.mm, macosx/coremidi/JackCoreMidiPort.h, macosx/coremidi/JackCoreMidiPort.mm, windows/winmme/JackWinMMEDriver.cpp, windows/winmme/JackWinMMEInputPort.cpp, windows/winmme/JackWinMMEOutputPort.cpp, windows/winmme/JackWinMMEPort.cpp, windows/winmme/JackWinMMEPort.h
This patch makes JACK set the pretty name for each MIDI port on server startup. Currently the pretty name is equal to the MIDI device name as reported by the system MIDI implementation. The following JACK MIDI drivers have been modified:
alsarawmidi, coremidi, winmme
The pretty names are not updated if a previous value is found, ie. to avoid overwriting user defined values. A better implementation might set a new "device name" key property instead, but existing clients already rely on pretty names for presenting ports to the user (for example QjackCtl and Ardour).
There is an existing property key presumably for describing hardware (http://jackaudio.org/metadata/hardware). This patch also sets such property to the MIDI device name on server startup, overwriting any previous value found. …
=> MIDI port pretty names

linux/alsa/alsa_driver.c
On ALSA poll time out, retry polling after executing the recovery
=> Jack retry after poll timeout

linux/alsa/JackAlsaDriver.cpp, linux/alsa/JackAlsaDriver.h, linux/alsa/alsa_midi_impl.h, linux/alsa/alsa_midi_jackmp.cpp, linux/alsa/alsa_rawmidi.c, linux/alsa/alsa_seqmidi.c
This patch extends https://github.com/jackaudio/jack2/pull/498 by setting initial metadata also for ALSA `raw` and `seq` MIDI ports.
@falkTX what do you think about renaming` PortSetDeviceMetadata()` to `PortSetInitialMetadata()` ? I think the latter better explains what that method does. There is another lowercase version `jack_port_set_device_metadata()` in `alsa_midi_jackmp.cpp` that should also be renamed, just in case.
=> Set initial metadata for ALSA MIDI raw and seq ports

common/JackLibAPI.cpp, common/jack/metadata.h
Opening PR to leave space for discussion.
Keys were imported from https://github.com/drobilla/jackey project, leaving the URL exactly the same (they were using jackaudio.org) but now officially supported.
We need to write some description for the keys that were already there.
@drobilla since you did the new ones and are quite skilled on wording (being native english speaker), do you mind trying to write a description for the "old" jack metadata keys? (see the "..." header comments on this PR)
Thanks in advance!
=> Import metadata keys from jackey, cleanup and reorder definitions

common/JackEngine.cpp, common/JackEngine.h, common/JackLockedEngine.h, linux/alsa/JackAlsaDriver.cpp, linux/alsa/JackAlsaDriver.h, linux/alsa/alsa_midi_impl.h, linux/alsa/alsa_midi_jackmp.cpp, linux/alsa/alsa_rawmidi.c, linux/alsa/alsa_seqmidi.c, linux/alsarawmidi/JackALSARawMidiDriver.cpp, macosx/coremidi/JackCoreMidiDriver.mm, windows/winmme/JackWinMMEDriver.cpp
This PR continues https://github.com/jackaudio/jack2/pull/505 and https://github.com/jackaudio/jack2/pull/498 by renaming `PortSetDeviceMetadata` and `jack_port_set_device_metadata` to `PortSetDefaultMetadata` and `jack_port_set_default_metadata` respectively. I think these names better reflect the intention of those and make code more readable.
I previously proposed using `PortSetInitialMetadata` in https://github.com/jackaudio/jack2/pull/505, but think this naming is better.
=> Rename PortSetDeviceMetadata to PortSetDefaultMetadata

linux/alsarawmidi/JackALSARawMidiPort.cpp
Compiling with -Wcatch-value I got this warning:
../linux/alsarawmidi/JackALSARawMidiPort.cpp:112:29: warning: catching polymorphic type ‘class std::exception’ by value [-Wcatch-value=]
=> Fix warning: catching polymorphic type ‘class std::exception’ by value

doxyfile.in
Custom footer without date is not needed in documentation anymore.
That was an old Fedora patch, I thinks it's not needed anymore.
If that file is not present, doc compilation fails.
=> Fix compilation of documentation

common/JackDriverLoader.cpp, common/driver_interface.h, windows/JackPlatformPlug_os.h, windows/JackSystemDeps_os.h
Fixes loading drivers/internals if jack is installed in a directory with special characters.
=> Windows: Use widechar instead of char when loading drivers.

posix/JackSocketServerChannel.cpp, posix/JackSocketServerNotifyChannel.cpp
in this case LGPL code is compiled into one library with GPL code, but
the include is not necessary and may cause problems in case
these files are separated into their own library
Change-Id: I9fc2499d60d8f25a8714c7c39b7b36206d5c5cf5
Signed-off-by: Adam Miartus <external.adam.miartus@de.bosch.com>
=> jack: remove unnecessary GPL include from LGPL code

posix/JackPosixSemaphore.cpp
The feature test macro should be defined, not tested. See [Feature Test Macros](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html):
>    Macro: _POSIX_C_SOURCE
>    Define this macro to a positive integer to control which POSIX functionality is made available. The greater the value of this macro, the more functionality is made available.
>    ....
>    If you define this macro to a value greater than or equal to 200112L, then the functionality from the 2001 edition of the POSIX standard (IEEE Standard 1003.1-2001) is made available. 
sem_timedwait is defined if _POSIX_C_SOURCE >= 200112L, so define it as such. If a system does not support this, it will be undefined and there will be a compilation error.
=> use feature test macro correctly

linux/alsa/alsa_driver.c
poll may be interrupted due to signal, in that case print error log
=> alsa: add log in case of poll was interrupted

linux/alsa/alsa_driver.c
This is always an audible issue. Therefore print the corresponding error message also in non verbose mode.
=> alsa: in case of poll timeout print error

common/jack/systemdeps.h
Fixes the following errors:
```
C:\vcpkg\installed\x64-windows-static-md\include\jack/systemdeps.h(73): error C2371: 'int8_t': redefinition; different basic types
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\stdint.h(14): note: see declaration of 'int8_t'
C:\vcpkg\installed\x64-windows-static-md\include\jack/systemdeps.h(77): error C2371: 'int32_t': redefinition; different basic types
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\stdint.h(16): note: see declaration of 'int32_t'
C:\vcpkg\installed\x64-windows-static-md\include\jack/systemdeps.h(78): error C2371: 'uint32_t': redefinition; different basic types
C:\Program Files (x86)\Microsoft Visual …
```
=> systemdeps.h: define standard integer types correctly for MSVC

posix/JackNetUnixSocket.cpp
Functions defined in sys/time.h are used but header is not included
=> posix: socket: Add missing time header include

example-clients/jack_control
Prior to this, `jack_control dps dither s` would return an error.
=> Fix jack_control handling of dbus bytes

example-clients/jack_control
It is useful when scripting with `jack_control` to behave differently in the event of an error (invalid ALSA device, bad options, etc). This patch makes the script correctly return a non-zero exit status when there is an error.
=> jack_control: return a proper exit status on DBus exception

posix/JackFifo.h
Function argument list is not matching with implementation.
=> posix: fifo: use right prototype

common/jack/jack.h
jack_port_get_latency_range only returns meaningful values after ports get
connected, and that is signalled via the latency callback. Saying that it's
normally used in callbacks is too soft, the docs should make it clear that the
function is not very useful outside of the callback, because you don't know
whether the port is connected / whether the latency values changed.
=> Clarification about jack_port_get_latency_range().

README.rst
This badge links to a chart that shows where jack2 is the package ecosystem. ~Apologies,~ I was ~un~successful formatting the .rst so the badges could be side-by-side.
Edit: See https://github.com/luzpaz/jack2/blob/README-repology/README.rst
=> README: Add repology repository badge

windows/README_MINGW
- Make it clear it is not the official way to build JACK *for* Windows, but a way to build JACK *on* Windows.
- Update build instructions for JackRouter. These could be copied/moved to the jack-router repo at some stage. Since it is a small VS project there is not really much to explain, though.
=> Update README_MINGW to reflect 2020 changes

linux/JackLinuxFutex.cpp
SYS_futex is expected from system C library.
in glibc (/usr/include/bits/syscall.h defines it in terms of of NR_futex)
rv32 is using 64bit time_t from get go unlike other 32bit architectures
in glibc, therefore it wont have NR_futex defined but just NR_futex_time64
this aliases it to NR_futex so that SYS_futex is then defined for rv32
Upstream-Status: Pending
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> Use SYS_futex instead of __NR_futex

common/Jackdmp.cpp
`--help` and `--version` do not result in server failures.
Instead of returning the default `-1`, return a more reasonable `0`.
Closes #663.
=> Change returncodes of jackd on all successes to 0

macosx/coreaudio/JackCoreAudioAdapter.mm, macosx/coreaudio/JackCoreAudioDriver.mm
The compiler definition was incorrect. MAC_OS_X_VERSION_10_5 is always defined on MacOS 10.5 and higher. We need to check for the currently platform version.
=> Fixing macOS version API use

tools/jack_control
This bug was introduced here: https://github.com/jackaudio/jack2/commit/5d80e06c08019aaceca01fa34f0cfa3b3fb73653#diff-7d08f37916cbe03a6368b218295081808a648cfe8d849d5b29326eb9228ed501R400
We use this script loads. Could I become the "maintainer" of it? If so, what the versions of Python does jack2 support?
Fixes issue: https://github.com/jackaudio/jack2/issues/652
Thanks, Pete.
=> Fix bug stopping jack_control doing many ops per execution

tools/midi_dump.c
The main loop might be blocked by `data_ready` when JACK server dies
while the program is running.
To reproduce the problem:
1. Start JACK server
2. Run `jack_midi_dump`
3. Stop JACK server
4. Press Ctrl-C in `jack_midi_dump` to send SIGINT.
5. Observe that the program doesn't stop and stuck in the main loop.
This patch forces the `data_ready` to be signaled in the signal handler
to prevent indefinite waiting.
=> fix a deadlock issue in midi_dump

common/JackClient.cpp, linux/JackLinuxFutex.cpp
FUTEX_WAIT may be interrupted by a signal and return EINTR. If a client
process takes a signal while on the futex, the jack client may error out
with no way to recover despite the signal being safe. Instead, retry if
errno is set to EINTR.
=> JackLinuxFutex: treat maximum TimedWait() as Wait() and retry on EINTR

common/JackActivationCount.h, common/JackAtomicArrayState.h, common/JackAtomicState.h, common/JackConnectionManager.cpp, common/JackConnectionManager.h, common/JackEngineControl.h, common/JackMessageBuffer.cpp, common/JackMessageBuffer.h, common/JackTransportEngine.cpp, common/JackTransportEngine.h, macosx/JackAtomic_os.h
Fix for issue #749.
Atomic accesses on AArch64 require atomically accessed fields to be naturally aligned. The packed structure layouts used on macOS to ensure than x86 and ARM processes can share memory breaks this constraint in some instances.
This change
1. Introduces alignment checks that ensure atomically-accessed fields are aligned within their parent structure (and that these parent structures are aligned within any struct containing them). These checks are static and have no runtime overhead.
2. Changes order of some fields, and adds some padding in one instance, to meet the alignment constraints.
=> Fix alignment of fields for atomic accesses

common/JackAPI.cpp
With some compilers and platforms `__STDC_FORMAT_MACROS` needs to be defined before anything else, as stated in the notes of the C++ refence: https://en.cppreference.com/w/cpp/types/integer#Notes. 
I was seeing issues on gcc like those of #408 and https://stackoverflow.com/questions/52715250/strange-compiler-behavior-with-priu64-in-c
=> __STDC_FORMAT_MACROS needs to be first

common/jack/types.h
This PR adds `tick_double` to `jack_position_t` and `JackTickDouble` as a validation flag for it.
Since older versions of JACK do not expose this variable, the macro JACK_TICK_DOUBLE is provided, which can be used as build-time detection.
Example code for transport-listening clients:
```
double tick;
#ifdef JACK_TICK_DOUBLE
if (pos.valid & JackTickDouble)
tick = pos.tick_double;
else
#endif
tick = pos.tick;
```
Rationale:
When using JACK transport to sync between clients with precise timing requirements (such as MIDI sequencers) rounding errors would accumulate and eventually make the separate clients out of sync.
This was observed in Carla and mod-host, which use audio plugins as JACK clients. Some MIDI plugins could miss notes due to rounding errors. This change has been deployed in MOD …
=> Add jack_position_t::tick_double, and flags around it

example-clients/wscript
It uses c++ sources and runtime therefore its best to use c++ compiler
to build it so it can find the correct runtime, cross compiling with
clang fails
x86_64-yoe-linux-ld: example-clients/simdtests.cpp.28.o: undefined reference to symbol '__cxa_call_unexpected@@CXXABI_1.3'
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> example-clients: Use c++ compiler for jack_simdtests

AUTHORS.rst, common/wscript, macosx/JackMachSemaphore.h, macosx/JackMachSemaphore.mm, macosx/JackMachSemaphoreServer.h, macosx/JackMachSemaphoreServer.mm, macosx/JackMachUtils.h
Previously, JackMachSemaphore would communicate the send right for the
semaphore object from the server to a client via a named service
registered via `bootstrap_register`. However, to do this, it would
register the semaphore's port as the service port directly.
In theory this ought to be fine, however in practice, macOS `launchd`,
which provides the `bootstrap_register` interface, does not correctly
detect when such a port becomes dead, and incorrectly believes that the
service that it provides is forever alive, even past the end of the
`jackd` process' (and therefore the semaphore's) existence. This seems
to be *specific* to semaphore ports, as `launchd` is expecting a
standard IPC port, owned by the task, not the kernel. This prevents
`jackd` from later registering another service with …
=> macOS: Pass JackMachSemaphore send right via mach_msg IPC

common/memops.c, common/memops.h, example-clients/simdtests.cpp, linux/alsa/alsa_driver.c, tools/alsa_in.c, tools/alsa_out.c
ALSA S24_LE is using the **lower** 3 bytes, not the upper.
> [Signed 24 bit Little Endian using low three bytes in 32-bit word](https://git.alsa-project.org/?p=alsa-lib.git;a=blob;f=include/pcm.h#l140)
This patch adds the memops for all 32l24 conversions like 32u24, and use them for ALSA driver only.
Maybe some other driver should use this too (OSS/Boomer) but I can not test them.
SIMD optimizations have been checked on ARM NEON and x86 SSE2.
Fixes jackaudio/jack2#459
=> ALSA: convert properly S24_LE

jack.pc.in
jack.pc.in:
Add the custom `jack_implementation=jack2` pkgconfig variable to the
generated jack.pc file to be able to distinguish jack implementations.
As jack implementations exist with jack1, jack2 and pipewire-jack, it is
not (easily) possible to distinguish them by looking at the version
alone (particularly the case with jack2 vs. pipewire-jack, as they share
the same headers).
=> Add custom variable to jack pkgconfig to distinguish implementations

ChangeLog.rst, man/fill_template, man/wscript, wscript
This allows for omitting the build and installation of libraries, executables and man pages provided by [jack-example-tools](https://github.com/jackaudio/jack-example-tools), by setting the new configure flag `--example-tools` (which currently defaults to `"yes"`) to `"no"`.
Additionally, this PR fixes many syntax problems in the top-level wscript file.
Fixes #805
=> Optional example clients and tools

wscript
wscript:
In 61a708f2c6873881ae36fa2f01b38a15bfc3f681 a regression has been
introduced, that always leads to not building the jack-example-tools
(even if selected).
This has been introduced due to the use of the wrong configuration
environment `HAVE_JACK_EXAMPLE_TOOLS`, whereas it should have been
`BUILD_JACK_EXAMPLE_TOOLS`.
Related to #805
=> Fix build of jack-example-tools with waf autooptions

.cirrus.yml
When the github application Cirrus CI (https://cirrus-ci.org/) is
installed, this build description file adds FreeBSD build checks to
changes and PRs in github.
There are four build tasks currently, a minimal build and one with all
options enabled on two different FreeBSD versions.
Unfortunately I don't see any other option of adding FreeBSD CI builds. But Cirrus CI has been quite unintrusive to me.
You can install the Cirrus CI Application from the Marketplace - choose the _public repositories only_ option (free) and select the repositories that use it. That will add the FreeBSD CI build checks to every change and PR that has this description file.
As a demo you can see what it looks like in my private repo:
https://github.com/0EVSG/jack2/tree/feature/freebsd_cirrus
=> CI: Add FreeBSD builds through Cirrus CI.

freebsd/oss/JackOSSDriver.cpp, man/jackd.0, solaris/oss/JackOSSDriver.cpp
Did a short check of the man page and saw that --excl was missing. The other options seem to be fine, I left out the --device option because it is redundant and its short version -d may be confused with the driver backend -d.
While there, also improve the short description of the excl option in the OSS backend part of usage help and jack_control.
The options of the FreeBSD and Solaris OSS backends are kept compatible, intentionally.
Is there anything more to man page QA, apart from spellcheck?
=> FreeBSD: Add missing OSS option --excl to man page.

common/JackMetadata.cpp
I have issues on computer wits several user accounts and jack2 and jack2-dbus installed. It looks like dbus uses UID and GID of current user and mask 027 for starting jack2
```
[root@arch shm]# ls -la
total 72
drwxr-x---  2 me me   120 Dec  5 11:57 jack_db
[root@arch shm]# ls -la jack_db/
total 324
drwxr-x--- 2 me me    120 Dec  5 11:57 .
drwxrwxrwt 4 root     root        100 Dec  5 12:58 ..
-rw-r----- 1 me me  393216 Dec  5 11:57 __db.001
-rw-r----- 1 me me  49152 Dec  5 11:57 __db.002
-rw-r----- 1 me me  49152 Dec  5 11:57 __db.003
-rw-r--r-- 1 me me  12288 Dec  5 11:57 metadata.db
```
Effectively, other user can't connect to metadata. There is a lot of reports out of github in regarding this issue as well.
Proposed PR is about to handle metadata of all users separately, as it was in …
=> Override permission issues by separating users metadata

common/jack/control.h, common/jack/jack.h, common/jack/midiport.h, common/jack/thread.h, common/jack/transport.h, common/jack/weakjack.h
Since doxygen 1.8.16, opening and closing a group must not be done as C comment but as doxygen command. In other words, not one but two asterisk characters are required so that doxygen finds a group. This fixed:
```
common/jack/control.h:659: warning: end of file while inside a group
common/jack/jack.h:1478: warning: end of file while inside a group
common/jack/midiport.h:198: warning: end of file while inside a group
common/jack/thread.h:161: warning: end of file while inside a group
common/jack/transport.h:248: warning: end of file while inside a group
common/jack/weakjack.h:126: warning: end of file while inside a group
```
Then, the removal of a superfluous closing at jack.h:560 fixed:
```
common/jack/jack.h:622: warning: unbalanced grouping commands
```
The changes at line 1054 and …
=> Fix grouping for latest doxygen.

common/memops.c, common/memops.h, linux/alsa/alsa_driver.c
Fixes #810 
adds new memops functions to convert 32 ints to float and float to 32 bit ints
uses doubles as intermediaries for a sign extension.
I haven't added SIMD instructions for x86 as I'm not too familiar with them and was having issues writing something that works.
Neon instructions were close enough to the original 24 bit versions for me to be able to port them over.
=> Add 32 bit support for ALSA driver

common/JackError.cpp, common/JackError.h
The function pointers `jack_error_callback` and `jack_info_callback` are
offered by the jack.h header as non-weak API members, but they were not
exported to the jack library, only to the jackserver library.
This broke the Jack backend of the OpenAl Soft library when switching
from Jack1 to Jack2.
Some archeological references: #226, kcat/openal-soft#138, kcat/openal-soft#139
Alternative solution: Mark `jack_error_callback` and `jack_info_callback` as deprecated and export them as weak symbols. OpenAl Soft library already handles `jack_error_callback` like a weak symbol, and I'm not aware of any other software that is affected.
@falkTX: Do we need some additional reviewers / opinions on that?
=> API: Export missing symbols to jack library.

man/wscript
Commit e8c0be1ce932bfb99fdd1a50e08fab187efed6ca changed the name
of the configuration environment to build the jack-example-tools,
but forgot to change it for man pages.
=> Fix build of jack-example-tools man pages

windows/inno/win32.iss, windows/inno/win64.iss
This DLL is required to have a proper Qt skin on Windows.
For a proper installer build using PawPaw, this PR requires https://github.com/DISTRHO/PawPaw/pull/25.
=> installer: add qwindowsvistastyle.dll for QJackCtl

common/JackAtomicArrayState.h, common/JackAtomicState.h, common/JackConnectionManager.h, common/JackEngineControl.h
Unbreak the build with Clang on architectures where JACK uses non-packed
data structures, like arm64 or powerpc. The alignment errors are exposed
there because:
* The non-packed data structures require 8 byte alignment.
* alignas() is not allowed to weaken alignment requirements to 4 bytes.
* Clang enforces this according to standard, GCC ignores it.
Use an additional alignas() specifier to let the compiler choose between
minimum alignment (packed) and "natural" alignment (non-packed). This is
both standard c++11 and compatible with older GCC, which does not
propagate alignment requirements of packed substructures properly.
To the best of my knowledge, this does not change ABI on any platform.
Please note that JACK explicitly uses packed data structures on MacOS,
that's why it wasn't …
=> Fix alignas() on non-packed architectures (#839).

posix/JackFifo.cpp
When using as sync opbject the given 'value' is meant to
already 'unblock' for that amount of Wait calls.
Signed-off-by: Andreas Pape <apape@de.adit-jv.com>
=> JackFifo: Apply given init value in allocate

.flake8, .github/workflows/build.yml, .github/workflows/lint.yml, .gitignore, common/wscript, compat/alloca/wscript, compat/wscript, dbus/wscript, example-clients/wscript, tests/wscript, tools/wscript, wscript
This fixes the Python syntax in all wscripts (excluding man/wscript, as it is fixed by #825). The fixes include:
* all wscripts are allowed a line length of 120 chars
* unused imports are removed
* moves file-wide imports to top of file
* general syntax fixes according to flake8 recommendations
* adds a flake8 configuration file and runs flake8 against all wscripts in CI
* allows for the IIO driver to be built (picks up source files correctly)
This allows for better readability and detection of errors. Running flake8 can be included in CI as well.
=> Fix wscripts syntax

common/jack/ringbuffer.h, common/ringbuffer.c
This patch addresses the thread safety problem of `jack_ringbuffer_t`
mentioned in #715 and #388. The overbound read bug caused by this problem
is impossible to reproduce on x86 due to its strong memory ordering, but
it is a problem on ARM and other weakly ordered architectures.
Basically, the main problem is that, on a weakly ordered architecture,
it is possible that the pointer increment after `memcpy` becomes visible
to the other thread before `memcpy` finishes:
memcpy (&(rb->buf[rb->write_ptr]), src, n1);
// vvv can be visible to reading thread before memcpy finishes
rb->write_ptr = (rb->write_ptr + n1) & rb->size_mask;
If this happens, the other thread can read the remaining garbage values
in `rb->buf` due to be overwritten by the unfinished `memcpy`.
To fix this, an explicit pair of …
=> Fix ringbuffer thread safety on ARM. Fix #715 #388

waflib/ConfigSet.py, waflib/Context.py
The 'U' mode bit is removed in python 3.11. It has been
deprecated for a long time. The 'U' mode bit has no effect
so this change doesn't change any behavior.
See https://docs.python.org/3.11/whatsnew/3.11.html#changes-in-the-python-api
=> Remove usage of 'U' mode bit for opening files in python
